'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const signing=import('../scripts/sign-macos.mjs');
function input(){const app='/synthetic/Mesh.app';return{app,arch:'arm64',app_version:'0.1.1',core_version:'0.42.16',source:'a'.repeat(40),team_id:'FIXTURE123',identity:'Developer ID Application: Mesh (FIXTURE123)',inner:[app+'/Contents/Resources/mesh-core/mesh-desktop-core',app+'/Contents/MacOS/Mesh']};}
const output='Identifier=com.brightinteraction.mesh.desktop\nFormat=app bundle with Mach-O thin (arm64)\nCodeDirectory v=20500 size=1 flags=0x10000(runtime)\nTeamIdentifier=FIXTURE123\nAuthority=Developer ID Application: Mesh (FIXTURE123)\nAuthority=Developer ID Certification Authority\nAuthority=Apple Root CA\nTimestamp=synthetic timestamp\n# designated => identifier "com.brightinteraction.mesh.desktop" and certificate leaf[subject.OU] = "FIXTURE123"';
test('signing preparation has no executable default and refuses ad-hoc, team, architecture and nested path mismatch',async()=>{const{signingPlan,inspectSigningOutput,exerciseSyntheticPlan}=await signing,p=signingPlan(input());assert.equal(p.disabled,true);assert.throws(()=>signingPlan({...input(),identity:'-'}));assert.throws(()=>signingPlan({...input(),inner:['/synthetic/Mesh.app/Contents/../../escape']}));assert.equal(inspectSigningOutput(output,p),true);for(const bad of [output+'\nSignature=adhoc',output.replace('FIXTURE123','WRONG12345'),output.replace('arm64','x86_64'),output.replace('Timestamp=synthetic timestamp',''),output.replace('(runtime)','(adhoc)')])assert.throws(()=>inspectSigningOutput(bad,p));await assert.rejects(exerciseSyntheticPlan(p,{fixture:false}),/DISABLED/);});
test('synthetic signing order binds final core before outer seal and freezes only the accepted notarized/stapled final ZIP',async()=>{const{signingPlan,exerciseSyntheticPlan}=await signing,p=signingPlan(input()),seen=[];const result=await exerciseSyntheticPlan(p,{fixture:true,run:async step=>{seen.push(step.phase);return{status:0,output,notary_status:'Accepted',submission_id:'synthetic-no-account'};},bindCore:async()=>{seen.push('bind-core');return{sha256:'b'.repeat(64),source:p.source,version:p.core_version};},finalZip:async()=>{seen.push('freeze');return Buffer.from('synthetic ZIP bytes, not a signed app');}});assert.equal(result.distribution_signed,false);assert.ok(seen.indexOf('bind-core')<seen.indexOf('outer'));assert.ok(seen.indexOf('staple-verify')<seen.indexOf('zip'));assert.equal(seen.at(-1),'freeze');assert.equal(result.commands.at(-1).size,37);
 await assert.rejects(exerciseSyntheticPlan(p,{fixture:true,run:async()=>({status:0,output,notary_status:'Invalid',submission_id:'synthetic'}),bindCore:async()=>({sha256:'b'.repeat(64),source:p.source,version:p.core_version}),finalZip:async()=>Buffer.from('must not be reached')}),/NOTARIZATION/);
});
