'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events'),{Readable}=require('node:stream'),{createHash}=require('node:crypto');
const {PreparedUpdater,ReleaseLedger,heldBlob,transfer,configureUpdater}=require('../src/updater.cjs');
const {crc32}=require('../src/release-contract.cjs');
const hash=b=>createHash('sha256').update(b).digest('hex');
function packageBytes(){const core=Buffer.alloc(40);core.writeUInt32LE(0xfeedfacf);core.writeUInt32LE(0x0100000c,4);const files=[['Mesh.app/Contents/Info.plist','<plist version="1.0"><dict><key>CFBundleIdentifier</key><string>com.brightinteraction.mesh.desktop</string><key>CFBundleShortVersionString</key><string>0.1.1</string><key>CFBundleVersion</key><string>0.1.1</string><key>ElectronSquirrelPreventDowngrades</key><true/></dict></plist>'],['Mesh.app/Contents/Resources/mesh-core/core.json',JSON.stringify({protocol:1,version:'0.42.16',source:'a'.repeat(40),platform:'darwin',arch:'arm64',sha256:hash(core)})],['Mesh.app/Contents/Resources/mesh-core/mesh-desktop-core',core],['Mesh.app/Contents/MacOS/Mesh',core]],locals=[],central=[];let offset=0;for(const[name,value]of files){const d=Buffer.from(value),n=Buffer.from(name),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt32LE(crc32(d),14);l.writeUInt32LE(d.length,18);l.writeUInt32LE(d.length,22);l.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(0x0314,4);c.writeUInt16LE(20,6);c.writeUInt32LE(crc32(d),16);c.writeUInt32LE(d.length,20);c.writeUInt32LE(d.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(0x81ed0000,38);c.writeUInt32LE(offset,42);locals.push(l,n,d);central.push(c,n);offset+=30+n.length+d.length;}const cb=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cb.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,cb,end]);}
function descriptor(bytes){return{schema:1,product:'mesh-desktop',channel:'stable',bundle_id:'com.brightinteraction.mesh.desktop',platform:'darwin',arch:'arm64',app_version:'0.1.1',core:{protocol:1,version:'0.42.16',source:'a'.repeat(40),arch:'arm64'},artifact:{url:'https://mesh.brightinteraction.com/desktop/releases/0.1.1/Mesh-0.1.1-arm64.zip',size:bytes.length,sha256:hash(bytes)},signing:{team_id:'FIXTURE123',notarized:true},provenance:{source:'a'.repeat(40),checks_sha256:'b'.repeat(64),approval_sha256:'c'.repeat(64)}};}
function transport(responses,calls=[]){return(url,options,callback)=>{calls.push({url,options});const req=new EventEmitter();req.destroy=()=>{};setImmediate(()=>{const value=responses.shift();if(value.error){req.emit('error',new Error('fixture disconnect'));return;}const response=Readable.from(value.parts||[value.bytes]);response.statusCode=value.status||200;response.headers=value.headers||{'content-type':url.endsWith('.json')?'application/json':'application/zip','content-length':String(value.bytes.length)};callback(response);});return req;};}
async function fixture({admit=async()=>true}={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'mesh-updater-')),bytes=packageBytes(),release=descriptor(bytes),calls=[],native=new EventEmitter();let checked=0,installed=0;native.setFeedURL=v=>{native.feed=v;};native.checkForUpdates=()=>{checked++;setImmediate(()=>native.emit('update-downloaded'));};native.quitAndInstall=()=>installed++;
 const updater=new PreparedUpdater({native,installed:{arch:'arm64',platform:'darwin',bundle_id:release.bundle_id,app_version:'0.1.0',team_id:'FIXTURE123',distribution_signed:true,notarized:true},admit,ledger:new ReleaseLedger(root),request:transport([{bytes:Buffer.from(JSON.stringify(release))},{bytes}],calls),temporary:root,stageTimeout:20});return{root,updater,release,bytes,calls,native,get checked(){return checked;},get installed(){return installed;},async close(){await updater.dispose();await fs.rm(root,{recursive:true,force:true});}};}
test('configured application remains disabled and renderer-style channel objects cannot enable the prepared provider',async()=>{
 assert.equal(configureUpdater(null).status().state,'disabled');assert.throws(()=>configureUpdater({origin:'https://mesh.brightinteraction.com'}),/UNAPPROVED/);await assert.rejects(configureUpdater(null).check(),/DISABLED/);
});
test('held blob is read-only, unlinked, hash-stable and positioned validation does not consume the native FD offset',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'mesh-held-'));let blob;try{blob=await heldBlob(root,w=>w.writeFile('immutable fixture'));assert.equal((await blob.handle.stat()).nlink,0);assert.equal((await fs.readdir(root)).length,0);assert.equal(blob.sha256,hash(Buffer.from('immutable fixture')));await assert.rejects(blob.handle.write(Buffer.from('evil')));const b=Buffer.alloc(17);assert.equal((await blob.handle.read(b,0,17,null)).bytesRead,17);assert.equal(b.toString(),'immutable fixture');}finally{await blob?.dispose();await fs.rm(root,{recursive:true,force:true});}
});
test('predownload does not stage; native gets only exact local feed/ZIP after confirmed drain, then installs once',async()=>{
 const f=await fixture();try{await f.updater.check();assert.equal(f.checked,0);assert.equal(f.installed,0);assert.equal(f.updater.status().state,'available');assert.deepEqual(f.calls.map(c=>Object.keys(c.options.headers)),[['Accept'],['Accept']]);
 await assert.rejects(f.updater.install({drain:async()=>{throw new Error('DIRTY');}}),/DIRTY/);assert.equal(f.checked,0);
 const archive=f.updater.blobs[0],feed=f.updater.blobs[1],b=Buffer.alloc(feed.size);await feed.handle.read(b,0,b.length,0);const normalized=JSON.parse(b);assert.equal(normalized.releases[0].updateTo.url,archive.url);assert.equal(normalized.releases[0].updateTo.sha256,hash(f.bytes));assert.equal((await archive.handle.stat()).nlink,0);
 let drained=false;await f.updater.install({drain:async()=>{drained=true;}});assert.equal(drained,true);assert.equal(f.checked,1);assert.equal(f.installed,1);assert.deepEqual(f.native.feed,{url:feed.url,serverType:'json'});await assert.rejects(f.updater.install({drain:async()=>{}}));
 }finally{await f.close();}
});
test('untrusted provenance is refused before archive fetch and native staging',async()=>{
 const f=await fixture({admit:async()=>false});try{await assert.rejects(f.updater.check(),/UNAPPROVED_RELEASE/);assert.equal(f.calls.length,1);assert.equal(f.checked,0);assert.equal(f.updater.blobs.length,0);}finally{await f.close();}
});
test('transport refuses redirects, foreign URLs, wrong sizes/hashes, range responses, body overflow and interruption without staging',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'mesh-transfer-'));try{
  const url='https://mesh.brightinteraction.com/desktop/releases/0.1.1/Mesh-0.1.1-arm64.zip';
  for(const response of [{bytes:Buffer.from('x'),status:302,headers:{location:'https://evil.invalid'}},{bytes:Buffer.from('x'),headers:{'content-type':'application/zip','content-length':'999'}},{bytes:Buffer.from('x'),headers:{'content-type':'application/zip','content-range':'bytes 0-0/1'}},{parts:[Buffer.from('xxx')],headers:{'content-type':'application/zip'}},{bytes:Buffer.from('y')},{error:true}]){const calls=[];await assert.rejects(heldBlob(root,w=>transfer(url,{limit:2,size:1,sha256:hash(Buffer.from('x')),kind:'archive',writer:w,request:transport([response],calls)})));assert.equal(calls.length,1);assert.equal((await fs.readdir(root)).length,0);}
  await assert.rejects(transfer('https://evil.invalid/update.zip',{limit:2,writer:{},request:()=>assert.fail('must not request')}),/FORBIDDEN/);
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
test('durable immutable slot survives a new provider and refuses changed source proof even when ZIP bytes match',async()=>{
 const f=await fixture();try{await f.updater.check();const ledger=new ReleaseLedger(f.root);assert.equal((await ledger.load())['0.1.1'].sha256,hash(f.bytes));await ledger.remember(f.release);const changed=structuredClone(f.release);changed.provenance.approval_sha256='d'.repeat(64);await assert.rejects(ledger.remember(changed),/COLLISION/);assert.equal((await new ReleaseLedger(f.root).load())['0.1.1'].sha256,hash(f.bytes));}finally{await f.close();}
});
test('native error after confirmed drain is uncertain, retains pinned descriptors and refuses automatic retry',async()=>{
 const f=await fixture();try{await f.updater.check();f.native.checkForUpdates=()=>setImmediate(()=>f.native.emit('error',new Error('fixture failure')));await assert.rejects(f.updater.install({drain:async()=>{}}),/UNCERTAIN/);assert.equal(f.updater.status().state,'uncertain');assert.equal(f.installed,0);assert.equal(f.updater.blobs.length,2);await assert.rejects(f.updater.check(),/BUSY/);}finally{await f.close();}
});

test('exclusive durable ledger refuses concurrent writers and stale lock instead of silently taking authority',async()=>{
 const f=await fixture();try{const lock=path.join(f.root,'release-slots.lock');await fs.writeFile(lock,'fixture owner',{mode:0o600});await assert.rejects(f.updater.ledger.remember(f.release),/LEDGER_LOCKED/);assert.equal(await fs.readFile(lock,'utf8'),'fixture owner');await fs.unlink(lock);await f.updater.ledger.remember(f.release);assert.equal((await new ReleaseLedger(f.root).load())['0.1.1'].source,'a'.repeat(40));}finally{await f.close();}
});

test('withdrawn admission after predownload is freshly refused before native staging even after the vault drained',async()=>{
 let calls=0;const f=await fixture({admit:async()=>++calls===1});try{await f.updater.check();let drained=false;await assert.rejects(f.updater.install({drain:async()=>{drained=true;}}),/UNAPPROVED_RELEASE/);assert.equal(drained,true);assert.equal(calls,2);assert.equal(f.checked,0);assert.equal(f.installed,0);assert.equal(f.updater.status().state,'uncertain');}finally{await f.close();}
});
